# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: bottlenet

before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod tidy
builds:
  -
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/minio/bottlenet/pkg.ReleaseTag={{.Tag}} -X github.com/minio/bottlenet/pkg.CommitID={{.FullCommit}} -X github.com/minio/bottlenet/pkg.Version={{.Version}} -X github.com/minio/bottlenet/pkg.ShortCommitID={{.ShortCommit}} -X github.com/minio/bottlenet/pkg.ReleaseTime={{.Date}}
archives:
  -
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: 'snapshot-{{ time "2006-01-02" }}'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
nfpms:
  -
    vendor: MinIO Inc.
    homepage: https://github.com/minio/bottlenet
    maintainer: MinIO <minio@minio.io>
    description: Find network bottlenecks
    license: GNU Affero General Public License v3.0
    formats:
      - deb
      - rpm
dockers:
  -
    # GOOS of the built binary that should be used.
    goos: linux
    # GOARCH of the built binary that should be used.
    goarch: amd64
    dockerfile: Dockerfile.release
    image_templates:
      - "minio/bottlenet:{{ .Tag }}"
      - "minio/bottlenet:latest"
